#!/bin/bash
echo "InfoHiC_lib = ${InfoHiC_lib}"
if [[ ! -s ${InfoHiC_lib}/post_analysis ]];then
        echo "set the InfoHiC_lib path correctly"
        exit 1
fi


target="sample1"
window_size=2Mb
true_matrix="NA"
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -m|--true_matrix)
      true_matrix="$2"
      shift
      shift
      ;;
    -w|--window)
      window_size="$2"
      shift
      shift
      ;;
    -h|--help)
      echo -e "Usage: InfoHiC_post <InfoHiC_output> [options]\n"
      echo -e "Options:"
      echo -e  "\t-w, --window (required) \n \t\t window size (1Mb, 2Mb)
\t-m, --true_matrix (optional) \n \t\t comparison with the true matrix. Enter a true matrix directory 
\t-h, --help\n
"

      exit 1
      ;;
    *)
     POSITIONAL+=("$1") # save it in an array for later
     shift
     ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters

InfoHiC_output=`readlink -f "$1"`
echo -e "InfoHiC_output = $InfoHiC_output"
if [[ $1 == "" ]] || [[ ! -s $InfoHiC_output ]];then
        echo "the InfoHiC_output doesn't exist"
        exit 1
fi


if [[ $true_matrix != "" ]] && [[ -s $true_matrix ]];then
        cis_path=$true_matrix\/chr_matrix
        trans_path=$true_matrix\/chr_matrix_trans
else
	cis_path=""
	trans_path=""
fi
echo "true_matrix = $true_matrix"


window=contigs.bed.sv_window
cd $InfoHiC_output\/karyotypes
while read -r -a l;do
	cd ${l[0]}
	if [ -s "ref.sv_window" ];then
		s=`echo ${l[0]} | awk '{n=split($1,f,"."); for(i=2;i<=n;i++){printf "%s\t", f[i];}; printf "\n";}'`
		${InfoHiC_lib}/post_analysis/true_format.sh "$s" $cis_path $trans_path  
		${InfoHiC_lib}/post_analysis/test_format.sh $window.class $target $window_size
		Rscript ${InfoHiC_lib}/post_analysis/format.R $target > 0.output 
		Rscript  ${InfoHiC_lib}/post_analysis/format_merge.R 
		mkdir -p ref_window 
		mkdir -p sv_window 
		Rscript ${InfoHiC_lib}/post_analysis/plot_format.R "true" 40
                Rscript ${InfoHiC_lib}/post_analysis/plot_format.R "test" 40
		Rscript ${InfoHiC_lib}/post_analysis/plot_format.R "all" 40
	fi
	i=1
	id=$target
	while read -r -a line;do
		s=${line[1]}
		e=$((${line[2]}-1))
		cat contig_out/class_predictions_$id\_$i\_${line[0]}_$s\_$e.txt |  awk -f ${InfoHiC_lib}/post_analysis/test_f_$window_size.awk | awk '{print "'${line[0]}'""\t"$1"\t""'${line[0]}'""\t"$2"\t"$3}' > $i.output
		cat contig_out_rc/class_predictions_$id\_$i\_${line[0]}_$s\_$e.txt |  awk -f ${InfoHiC_lib}/post_analysis/test_rc_$window_size.awk | awk '{print "'${line[0]}'""\t"$1"\t""'${line[0]}'""\t"$2"\t"$3}' >> $i.output
		Rscript ${InfoHiC_lib}/post_analysis/format_merge_contig.R $i.output $i.output.format
		cat $i.output.format  |  awk '{if($2>0 && $4>0) print $0}' > $i.output.format.v
		Rscript ${InfoHiC_lib}/post_analysis/tad.R $i.output.format.v 20
		cat contigs.index.sv | awk '{if($1=="'${line[0]}'" && $2 >= '"$s"' && $2<= '"$e"' ) print $0}' > $i.index.sv
		cat contigs.index.ens | awk '{ if($3=="'${line[0]}'" && $5 >= '"$s"' && $6<= '"$e"' ) print $0}' > $i.index.ens
		cat contigs.index.se| awk '{ if($3=="'${line[0]}'" && $5 >= '"$s"' && $6<= '"$e"' ) print $0}' > $i.index.se
		cat contigs.index.te| awk '{ if($3=="'${line[0]}'" && $5 >= '"$s"' && $6<= '"$e"' ) print $0}' > $i.index.te
		Rscript ${InfoHiC_lib}/post_analysis/plot_withtad_withloop.R $i.output.format.v 35 $i.output.format.v.tad $i.index.sv $i.index.ens $i.index.se  $i.index.te all null
		i=$(($i+1))
	done < contigs.bed.sv_window


	nc=`cat contigs.bed.sv_window | wc -l`
	for i in `seq 1 $nc`;do
		${InfoHiC_lib}/post_analysis/ICE.sh  $i
		python ${InfoHiC_lib}/post_analysis/neoloop_ICE.py $i > $i.index.neoloop.m
		Rscript ${InfoHiC_lib}/post_analysis/neoloop_ICE_nearsv.R $i
		Rscript ${InfoHiC_lib}/post_analysis/neoloop_ICE.R $i > $i.index.neoloop.ens.m
		Rscript ${InfoHiC_lib}/post_analysis/plot_withtad_withloop.R $i.output.m.format.v 30 $i.output.m.format.v.tad $i.index.sv $i.index.ens $i.index.se  $i.index.te all $i.index.neoloop.m
	done


	cd ../
done< euler.list
